print("Bitte geben Sie ein Symbol ein:")
symbol = input()
print("Ihr persönliches Dreieck")
print(symbol)
print(symbol * 2)
print(symbol * 3)
print(symbol * 4)
print(symbol * 5)
print(symbol * 6)
print(symbol * 7)
print(symbol * 8)
print(symbol * 9)
print(symbol * 10)
